apiVersion: apps/v1
kind: Deployment
metadata:
  name: soe-calendar-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: soe-calendar-frontend
        image: ghcr.io/sigmasuite/soe_calendar_front:main
        ports:
          - containerPort: 3000
    metadata:
      labels:
        service: soe-calendar-frontend
  selector:
    matchLabels:
      app: soe-calendar-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: soe-calendar-frontend
spec:
  type: ClusterIP
  selector:
    app: soe-calendar-frontend
  ports:
    - port: 3000
      targetPort: 3000
